services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: video2-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin123!
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: